# Site settings
title: Software, Travel, Life
email: eric@tabfugni.cc
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer. I like to travel and be outdoors. Every once in a great while I will write about it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tabfugnic.github.io" # the base hostname & protocol for your site
twitter_username: tabfugnic
github_username:  tabfugnic

# Build settings
markdown: kramdown
paginate: 5
permalink: pretty

gems: [jekyll-paginate]
