title: pixels, bits, and screws
email: eric@tabfugni.cc
description: >
  The confluence of writing software, people management, building
  products, and working with your hands.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tabfugni.cc"
twitter_username: tabfugnic
github_username:  tabfugnic
markdown: kramdown
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
theme_config:
  appearance: dark
  date_format: "%Y-%m-%d"
